services:
  bike_postgres:
    image: postgres:15.7
    container_name: bike_postgres
    ports:
      - "5433:5432"
    networks:
      - hadoop
    volumes:
      - ./bike_analytics_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: bike_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret

networks:
  hadoop:
    driver: bridge
