services:
  bike_postgres:
    image: postgres:15.7
    container_name: bike_postgres
    ports:
      - "5433:5432"
    networks:
      - hadoop
    volumes:
      - ./bike_analytics_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: bike_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - hadoop
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./bike_sales_vizualisation/grafana/provisioning:/etc/grafana/provisioning
      - ./bike_sales_vizualisation/grafana/dashboard:/var/lib/grafana/dashboards
    restart: on-failure

networks:
  hadoop:
    external: true

volumes:
  grafana_data: {}
