{
 "title": "Bike sales analytics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Tranche d'âge générant le plus de revenues",
   "type": "stat",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT * FROM age_group_purchases LIMIT 50 "
    }
   ]
  },
  {
   "title": "Revenu par sous catégories",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 7, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM sub_category_revenue LIMIT 50 "
    }
   ]
  },
  {
   "title": "Revenu par catégories de produits",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT * FROM category_revenue LIMIT 50 "
    }
   ]
  },
  {
   "title": "Top 10 produits en France",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT * FROM top_10_products_france LIMIT 50 "
    }
   ]
  },
  {
   "title": "Top 20 produits mondiaux",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT * FROM top_20_products_global LIMIT 50 "
    }
   ]
  }
 ]
}